//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Casestudyb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table("Login")]


    public class LoginModel
    {
        [Required(ErrorMessage = "Please enter user name")]
        [Display(Name = "User Name")]
        [StringLength(30)]
        public string UserName { get; set; }
        [Required(ErrorMessage = "Please enter user name")]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        [StringLength(10)]
        public string Pwdwrd { get; set; }
    }




    public partial class Customer
    {
        


        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]

        public int Customerid { get; set; }
        public string Customername { get; set; }
        public string Contactnumber { get; set; }
        public string Rcity { get; set; }
        public string Address { get; set; }
        public string UserName { get; set; }
        public string Pwdwrd { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orderfood> Orderfoods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orderstatu> Orderstatus { get; set; }
    }
}
