//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Casestudyb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orderstatu
    {
        public int Orderid { get; set; }
        public int Customerid { get; set; }
        public decimal Grandtotal { get; set; }
        public string Payment { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
