//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Casestudyb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orderfood
    {
        public int OrderFid { get; set; }
        public int Customerid { get; set; }
        public int Restaurantid { get; set; }
        public int Foodid { get; set; }
        public string Paymentmethod { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Fooditem Fooditem { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
