//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Casestudyb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table("Adminlogin")]

    public class AdminloginModel
    {
        [Required(ErrorMessage = "Please enter user name")]
        [Display(Name = "User Name")]
        [StringLength(30)]
        public string Usr { get; set; }
        [Required(ErrorMessage = "Please enter user name")]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        [StringLength(10)]
        public string Pwd { get; set; }
    }

    public partial class Userpassword
    {

        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]

        public int Id { get; set; }
        public string Usr { get; set; }
        public string Pwd { get; set; }
    }
}
